### ISSUE TITLE
Reloading code causes event to fire multiple times

### ISSUE THREAD

**Issue by pinzonjulian** [bibendi/downstream#6]
# Describe the bug
After reloading the code, events get processed multiple times.
### Example Event

![image](https://user-images.githubusercontent.com/10928518/148159839-62d276fc-7fb1-4c22-b8c1-2c80072f4334.png)

### Publishing event:

![image](https://user-images.githubusercontent.com/10928518/148159880-0d612c96-a259-4560-8456-404900f7776a.png)

### Event gets published and consumed correctly:

![image](https://user-images.githubusercontent.com/10928518/148159924-92401581-3a2c-4be9-9556-b9d2ca781fb1.png)

### Run `reload!` in Rails console. See how event gets published once but processed 3 times:

![image](https://user-images.githubusercontent.com/10928518/148160001-eeaf23f7-4a94-4c70-be30-916fbd341669.png)

### Reloading and publishing once more:

![image](https://user-images.githubusercontent.com/10928518/148160048-18df98b2-95ca-4cd4-987c-d4dfe04e6c81.png)

### Now the event gets consumed 5 times

![image](https://user-images.githubusercontent.com/10928518/148160078-166d2773-77cc-4134-8f82-dc713ab16fea.png)

In this scenario, reloading happens by calling `reload!` in the rails console but I also see this happening after I change something from my codebase and perform an action in the UI.

**To Reproduce**
1. Ruby version: 3.0.3
2. Rails version: 7.0.0. I'm using my own [fork](https://github.com/pinzonjulian/downstream/tree/using-rails-7) because I'm building an app on Rails 7. I believe this happens with 6 as well but I don't currently have an example of that.
3. Run command: 
    - Create event and subscriber. 
    - open rails console
    - initialise and publish event
    - reload console using `reload!`
    - initialise and publish event again
    - see how the event is processed multiple times

**Expected behavior**
I expect for events not to be multiplied.

**Context (please complete the following information):**
 - OS: MacOS
 - Version 11.5.2 Big Sur

# Example app
You can check out the example app I used to create this issue here:
https://github.com/pinzonjulian/downstream-duplicate-events

**Comment by bibendi** [comment]
Sorry for the long delay.
Please, try to define subscribes in an initializer like there https://github.com/bibendi/modular-rails/blob/46f7abe9701000f6c0abf6adcbf822045831a054/engines/interests/lib/interests/engine.rb#L31-L35
